services:
  api:
    container_name: fordox_api
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ../frontend:/app/frontend  # necessário para servir os HTML e estáticos
    env_file:
      - ../.env
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fordox_network

  frontend:
    container_name: fordox_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
    networks:
      - fordox_network

networks:
  fordox_network:
    driver: bridge
